# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cfd3c275e6cf6460478292a0631818b40e1891d7b78874df426b18f2c4e5009be02e6fd95efe354a540db7eba6be9e4667737f9e40f5bc8c9377bd993e43139

test:
  secret_key_base: ba074d881a5a1c8264cac9850e73ff4d40cdff2471e26b150c83b5f308be8b772b7016734bc58022504cf3205ce805680641b156ae64d7f6e9c2f7871a3c29bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
